/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alltogether extends org.jooq.impl.TableImpl<sooth.entities.tables.records.AlltogetherRecord> {

	private static final long serialVersionUID = 1387019908;

	/**
	 * The reference instance of <code>asmregen.alltogether</code>
	 */
	public static final sooth.entities.tables.Alltogether ALLTOGETHER = new sooth.entities.tables.Alltogether();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.AlltogetherRecord> getRecordType() {
		return sooth.entities.tables.records.AlltogetherRecord.class;
	}

	/**
	 * The column <code>asmregen.alltogether.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.alltogether.assignmentId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.Integer> ASSIGNMENTID = createField("assignmentId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.alltogether.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.alltogether.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.alltogether.pluginDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.String> PLUGINDESCRIPTION = createField("pluginDescription", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>asmregen.alltogether.deadline</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.sql.Timestamp> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.alltogether.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.alltogether.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.alltogether.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.alltogether.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.alltogether.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.alltogether.submissionsCount</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AlltogetherRecord, java.lang.Long> SUBMISSIONSCOUNT = createField("submissionsCount", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>asmregen.alltogether</code> table reference
	 */
	public Alltogether() {
		this("alltogether", null);
	}

	/**
	 * Create an aliased <code>asmregen.alltogether</code> table reference
	 */
	public Alltogether(java.lang.String alias) {
		this(alias, sooth.entities.tables.Alltogether.ALLTOGETHER);
	}

	private Alltogether(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AlltogetherRecord> aliased) {
		this(alias, aliased, null);
	}

	private Alltogether(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AlltogetherRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Alltogether as(java.lang.String alias) {
		return new sooth.entities.tables.Alltogether(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Alltogether rename(java.lang.String name) {
		return new sooth.entities.tables.Alltogether(name, null);
	}
}
