/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Assignmentsproblemslecturesgroups extends org.jooq.impl.TableImpl<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord> {

	private static final long serialVersionUID = -395971969;

	/**
	 * The reference instance of <code>asmregen.assignmentsproblemslecturesgroups</code>
	 */
	public static final sooth.entities.tables.Assignmentsproblemslecturesgroups ASSIGNMENTSPROBLEMSLECTURESGROUPS = new sooth.entities.tables.Assignmentsproblemslecturesgroups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord> getRecordType() {
		return sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord.class;
	}

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.problemId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.Integer> PROBLEMID = createField("problemId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.deadline</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.sql.Timestamp> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.groupType</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.String> GROUPTYPE = createField("groupType", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroups.pluginId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord, java.lang.Integer> PLUGINID = createField("pluginId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>asmregen.assignmentsproblemslecturesgroups</code> table reference
	 */
	public Assignmentsproblemslecturesgroups() {
		this("assignmentsproblemslecturesgroups", null);
	}

	/**
	 * Create an aliased <code>asmregen.assignmentsproblemslecturesgroups</code> table reference
	 */
	public Assignmentsproblemslecturesgroups(java.lang.String alias) {
		this(alias, sooth.entities.tables.Assignmentsproblemslecturesgroups.ASSIGNMENTSPROBLEMSLECTURESGROUPS);
	}

	private Assignmentsproblemslecturesgroups(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Assignmentsproblemslecturesgroups(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AssignmentsproblemslecturesgroupsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Assignmentsproblemslecturesgroups as(java.lang.String alias) {
		return new sooth.entities.tables.Assignmentsproblemslecturesgroups(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Assignmentsproblemslecturesgroups rename(java.lang.String name) {
		return new sooth.entities.tables.Assignmentsproblemslecturesgroups(name, null);
	}
}
