/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Assignmentsproblemslecturesgroupsplugins extends org.jooq.impl.TableImpl<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord> {

	private static final long serialVersionUID = 1100783565;

	/**
	 * The reference instance of <code>asmregen.assignmentsproblemslecturesgroupsplugins</code>
	 */
	public static final sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS = new sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord> getRecordType() {
		return sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord.class;
	}

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.Integer> PROBLEMID = createField("problemId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.pluginDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.String> PLUGINDESCRIPTION = createField("pluginDescription", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.deadline</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.sql.Timestamp> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupType</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.String> GROUPTYPE = createField("groupType", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>asmregen.assignmentsproblemslecturesgroupsplugins</code> table reference
	 */
	public Assignmentsproblemslecturesgroupsplugins() {
		this("assignmentsproblemslecturesgroupsplugins", null);
	}

	/**
	 * Create an aliased <code>asmregen.assignmentsproblemslecturesgroupsplugins</code> table reference
	 */
	public Assignmentsproblemslecturesgroupsplugins(java.lang.String alias) {
		this(alias, sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS);
	}

	private Assignmentsproblemslecturesgroupsplugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Assignmentsproblemslecturesgroupsplugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins as(java.lang.String alias) {
		return new sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins rename(java.lang.String name) {
		return new sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins(name, null);
	}
}
