/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Assignmentsproblemsplugins extends org.jooq.impl.TableImpl<sooth.entities.tables.records.AssignmentsproblemspluginsRecord> {

	private static final long serialVersionUID = 122863033;

	/**
	 * The reference instance of <code>asmregen.assignmentsproblemsplugins</code>
	 */
	public static final sooth.entities.tables.Assignmentsproblemsplugins ASSIGNMENTSPROBLEMSPLUGINS = new sooth.entities.tables.Assignmentsproblemsplugins();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.AssignmentsproblemspluginsRecord> getRecordType() {
		return sooth.entities.tables.records.AssignmentsproblemspluginsRecord.class;
	}

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.deadline</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.sql.Timestamp> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.problemConfig</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.String> PROBLEMCONFIG = createField("problemConfig", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.pluginName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.String> PLUGINNAME = createField("pluginName", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.pluginType</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.String> PLUGINTYPE = createField("pluginType", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.pluginDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.String> PLUGINDESCRIPTION = createField("pluginDescription", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.pluginMainFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.String> PLUGINMAINFILE = createField("pluginMainFile", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemsplugins.pluginConfig</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemspluginsRecord, java.lang.String> PLUGINCONFIG = createField("pluginConfig", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>asmregen.assignmentsproblemsplugins</code> table reference
	 */
	public Assignmentsproblemsplugins() {
		this("assignmentsproblemsplugins", null);
	}

	/**
	 * Create an aliased <code>asmregen.assignmentsproblemsplugins</code> table reference
	 */
	public Assignmentsproblemsplugins(java.lang.String alias) {
		this(alias, sooth.entities.tables.Assignmentsproblemsplugins.ASSIGNMENTSPROBLEMSPLUGINS);
	}

	private Assignmentsproblemsplugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AssignmentsproblemspluginsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Assignmentsproblemsplugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AssignmentsproblemspluginsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Assignmentsproblemsplugins as(java.lang.String alias) {
		return new sooth.entities.tables.Assignmentsproblemsplugins(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Assignmentsproblemsplugins rename(java.lang.String name) {
		return new sooth.entities.tables.Assignmentsproblemsplugins(name, null);
	}
}
