/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Assignmentsproblemslectures extends org.jooq.impl.TableImpl<sooth.entities.tables.records.AssignmentsproblemslecturesRecord> {

	private static final long serialVersionUID = -74813609;

	/**
	 * The reference instance of <code>asmregen.assignmentsproblemslectures</code>
	 */
	public static final sooth.entities.tables.Assignmentsproblemslectures ASSIGNMENTSPROBLEMSLECTURES = new sooth.entities.tables.Assignmentsproblemslectures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.AssignmentsproblemslecturesRecord> getRecordType() {
		return sooth.entities.tables.records.AssignmentsproblemslecturesRecord.class;
	}

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.problemId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.Integer> PROBLEMID = createField("problemId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.deadline</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.sql.Timestamp> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.assignmentsproblemslectures.pluginId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.AssignmentsproblemslecturesRecord, java.lang.Integer> PLUGINID = createField("pluginId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>asmregen.assignmentsproblemslectures</code> table reference
	 */
	public Assignmentsproblemslectures() {
		this("assignmentsproblemslectures", null);
	}

	/**
	 * Create an aliased <code>asmregen.assignmentsproblemslectures</code> table reference
	 */
	public Assignmentsproblemslectures(java.lang.String alias) {
		this(alias, sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES);
	}

	private Assignmentsproblemslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AssignmentsproblemslecturesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Assignmentsproblemslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.AssignmentsproblemslecturesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Assignmentsproblemslectures as(java.lang.String alias) {
		return new sooth.entities.tables.Assignmentsproblemslectures(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Assignmentsproblemslectures rename(java.lang.String name) {
		return new sooth.entities.tables.Assignmentsproblemslectures(name, null);
	}
}
