/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Groupslectures extends org.jooq.impl.TableImpl<sooth.entities.tables.records.GroupslecturesRecord> {

	private static final long serialVersionUID = 1921007788;

	/**
	 * The reference instance of <code>asmregen.groupslectures</code>
	 */
	public static final sooth.entities.tables.Groupslectures GROUPSLECTURES = new sooth.entities.tables.Groupslectures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.GroupslecturesRecord> getRecordType() {
		return sooth.entities.tables.records.GroupslecturesRecord.class;
	}

	/**
	 * The column <code>asmregen.groupslectures.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupslecturesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.groupslectures.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupslecturesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.groupslectures.description</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupslecturesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.groupslectures.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupslecturesRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.groupslectures.type</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupslecturesRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.groupslectures.lectureId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupslecturesRecord, java.lang.Integer> LECTUREID = createField("lectureId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.groupslectures.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupslecturesRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.groupslectures.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.GroupslecturesRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.groupslectures</code> table reference
	 */
	public Groupslectures() {
		this("groupslectures", null);
	}

	/**
	 * Create an aliased <code>asmregen.groupslectures</code> table reference
	 */
	public Groupslectures(java.lang.String alias) {
		this(alias, sooth.entities.tables.Groupslectures.GROUPSLECTURES);
	}

	private Groupslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.GroupslecturesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Groupslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.GroupslecturesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Groupslectures as(java.lang.String alias) {
		return new sooth.entities.tables.Groupslectures(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Groupslectures rename(java.lang.String name) {
		return new sooth.entities.tables.Groupslectures(name, null);
	}
}
