/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Problemsplugins extends org.jooq.impl.TableImpl<sooth.entities.tables.records.ProblemspluginsRecord> {

	private static final long serialVersionUID = 1749719268;

	/**
	 * The reference instance of <code>asmregen.problemsplugins</code>
	 */
	public static final sooth.entities.tables.Problemsplugins PROBLEMSPLUGINS = new sooth.entities.tables.Problemsplugins();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.ProblemspluginsRecord> getRecordType() {
		return sooth.entities.tables.records.ProblemspluginsRecord.class;
	}

	/**
	 * The column <code>asmregen.problemsplugins.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.problemsplugins.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.problemsplugins.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.problemsplugins.problemConfig</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.String> PROBLEMCONFIG = createField("problemConfig", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.problemsplugins.pluginName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.String> PLUGINNAME = createField("pluginName", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>asmregen.problemsplugins.pluginType</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.String> PLUGINTYPE = createField("pluginType", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>asmregen.problemsplugins.pluginDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.String> PLUGINDESCRIPTION = createField("pluginDescription", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>asmregen.problemsplugins.pluginMainFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.String> PLUGINMAINFILE = createField("pluginMainFile", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>asmregen.problemsplugins.pluginConfig</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.ProblemspluginsRecord, java.lang.String> PLUGINCONFIG = createField("pluginConfig", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>asmregen.problemsplugins</code> table reference
	 */
	public Problemsplugins() {
		this("problemsplugins", null);
	}

	/**
	 * Create an aliased <code>asmregen.problemsplugins</code> table reference
	 */
	public Problemsplugins(java.lang.String alias) {
		this(alias, sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS);
	}

	private Problemsplugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.ProblemspluginsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Problemsplugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.ProblemspluginsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Problemsplugins as(java.lang.String alias) {
		return new sooth.entities.tables.Problemsplugins(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Problemsplugins rename(java.lang.String name) {
		return new sooth.entities.tables.Problemsplugins(name, null);
	}
}
