/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Submissionsfullwithowners extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubmissionsfullwithownersRecord> {

	private static final long serialVersionUID = 875600482;

	/**
	 * The reference instance of <code>asmregen.submissionsfullwithowners</code>
	 */
	public static final sooth.entities.tables.Submissionsfullwithowners SUBMISSIONSFULLWITHOWNERS = new sooth.entities.tables.Submissionsfullwithowners();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubmissionsfullwithownersRecord> getRecordType() {
		return sooth.entities.tables.records.SubmissionsfullwithownersRecord.class;
	}

	/**
	 * The column <code>asmregen.submissionsfullwithowners.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.assignmentId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.Integer> ASSIGNMENTID = createField("assignmentId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.submissionFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> SUBMISSIONFILE = createField("submissionFile", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.date</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.status</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.success</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.Integer> SUCCESS = createField("success", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.info</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> INFO = createField("info", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.outputFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> OUTPUTFILE = createField("outputFile", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.rating</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.Integer> RATING = createField("rating", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.explanation</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> EXPLANATION = createField("explanation", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.deadline</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.sql.Timestamp> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsfullwithowners.realName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsfullwithownersRecord, java.lang.String> REALNAME = createField("realName", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * Create a <code>asmregen.submissionsfullwithowners</code> table reference
	 */
	public Submissionsfullwithowners() {
		this("submissionsfullwithowners", null);
	}

	/**
	 * Create an aliased <code>asmregen.submissionsfullwithowners</code> table reference
	 */
	public Submissionsfullwithowners(java.lang.String alias) {
		this(alias, sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS);
	}

	private Submissionsfullwithowners(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubmissionsfullwithownersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Submissionsfullwithowners(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubmissionsfullwithownersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Submissionsfullwithowners as(java.lang.String alias) {
		return new sooth.entities.tables.Submissionsfullwithowners(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Submissionsfullwithowners rename(java.lang.String name) {
		return new sooth.entities.tables.Submissionsfullwithowners(name, null);
	}
}
