/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Submissionsusers extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubmissionsusersRecord> {

	private static final long serialVersionUID = 1836285666;

	/**
	 * The reference instance of <code>asmregen.submissionsusers</code>
	 */
	public static final sooth.entities.tables.Submissionsusers SUBMISSIONSUSERS = new sooth.entities.tables.Submissionsusers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubmissionsusersRecord> getRecordType() {
		return sooth.entities.tables.records.SubmissionsusersRecord.class;
	}

	/**
	 * The column <code>asmregen.submissionsusers.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.assignmentId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.Integer> ASSIGNMENTID = createField("assignmentId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissionsusers.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissionsusers.realName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.String> REALNAME = createField("realName", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.submissionFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.String> SUBMISSIONFILE = createField("submissionFile", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.date</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.status</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.success</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.Integer> SUCCESS = createField("success", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.info</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.String> INFO = createField("info", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.outputFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.String> OUTPUTFILE = createField("outputFile", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.rating</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.Integer> RATING = createField("rating", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsusers.explanation</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsusersRecord, java.lang.String> EXPLANATION = createField("explanation", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.submissionsusers</code> table reference
	 */
	public Submissionsusers() {
		this("submissionsusers", null);
	}

	/**
	 * Create an aliased <code>asmregen.submissionsusers</code> table reference
	 */
	public Submissionsusers(java.lang.String alias) {
		this(alias, sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS);
	}

	private Submissionsusers(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubmissionsusersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Submissionsusers(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubmissionsusersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Submissionsusers as(java.lang.String alias) {
		return new sooth.entities.tables.Submissionsusers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Submissionsusers rename(java.lang.String name) {
		return new sooth.entities.tables.Submissionsusers(name, null);
	}
}
