/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Submissionsassignmentsproblemslecturesgroups extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord> {

	private static final long serialVersionUID = 254753442;

	/**
	 * The reference instance of <code>asmregen.submissionsassignmentsproblemslecturesgroups</code>
	 */
	public static final sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS = new sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord> getRecordType() {
		return sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord.class;
	}

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.assignmentId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> ASSIGNMENTID = createField("assignmentId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.submissionFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> SUBMISSIONFILE = createField("submissionFile", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.date</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.status</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.success</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> SUCCESS = createField("success", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.info</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> INFO = createField("info", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.outputFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> OUTPUTFILE = createField("outputFile", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.rating</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> RATING = createField("rating", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.explanation</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> EXPLANATION = createField("explanation", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.deadline</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.sql.Timestamp> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.submissionsassignmentsproblemslecturesgroups</code> table reference
	 */
	public Submissionsassignmentsproblemslecturesgroups() {
		this("submissionsassignmentsproblemslecturesgroups", null);
	}

	/**
	 * Create an aliased <code>asmregen.submissionsassignmentsproblemslecturesgroups</code> table reference
	 */
	public Submissionsassignmentsproblemslecturesgroups(java.lang.String alias) {
		this(alias, sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS);
	}

	private Submissionsassignmentsproblemslecturesgroups(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Submissionsassignmentsproblemslecturesgroups(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups as(java.lang.String alias) {
		return new sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups rename(java.lang.String name) {
		return new sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups(name, null);
	}
}
