/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subscriptionsusers extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubscriptionsusersRecord> {

	private static final long serialVersionUID = 265592036;

	/**
	 * The reference instance of <code>asmregen.subscriptionsusers</code>
	 */
	public static final sooth.entities.tables.Subscriptionsusers SUBSCRIPTIONSUSERS = new sooth.entities.tables.Subscriptionsusers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubscriptionsusersRecord> getRecordType() {
		return sooth.entities.tables.records.SubscriptionsusersRecord.class;
	}

	/**
	 * The column <code>asmregen.subscriptionsusers.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusers.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.subscriptionsusers.status</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusers.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusers.realName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersRecord, java.lang.String> REALNAME = createField("realName", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusers.email</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>asmregen.subscriptionsusers</code> table reference
	 */
	public Subscriptionsusers() {
		this("subscriptionsusers", null);
	}

	/**
	 * Create an aliased <code>asmregen.subscriptionsusers</code> table reference
	 */
	public Subscriptionsusers(java.lang.String alias) {
		this(alias, sooth.entities.tables.Subscriptionsusers.SUBSCRIPTIONSUSERS);
	}

	private Subscriptionsusers(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsusersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Subscriptionsusers(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsusersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Subscriptionsusers as(java.lang.String alias) {
		return new sooth.entities.tables.Subscriptionsusers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Subscriptionsusers rename(java.lang.String name) {
		return new sooth.entities.tables.Subscriptionsusers(name, null);
	}
}
