/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subscriptionsusersgroupslectures extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord> {

	private static final long serialVersionUID = -2078975499;

	/**
	 * The reference instance of <code>asmregen.subscriptionsusersgroupslectures</code>
	 */
	public static final sooth.entities.tables.Subscriptionsusersgroupslectures SUBSCRIPTIONSUSERSGROUPSLECTURES = new sooth.entities.tables.Subscriptionsusersgroupslectures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord> getRecordType() {
		return sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord.class;
	}

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.realName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.String> REALNAME = createField("realName", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.email</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsusersgroupslectures.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>asmregen.subscriptionsusersgroupslectures</code> table reference
	 */
	public Subscriptionsusersgroupslectures() {
		this("subscriptionsusersgroupslectures", null);
	}

	/**
	 * Create an aliased <code>asmregen.subscriptionsusersgroupslectures</code> table reference
	 */
	public Subscriptionsusersgroupslectures(java.lang.String alias) {
		this(alias, sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES);
	}

	private Subscriptionsusersgroupslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Subscriptionsusersgroupslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Subscriptionsusersgroupslectures as(java.lang.String alias) {
		return new sooth.entities.tables.Subscriptionsusersgroupslectures(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Subscriptionsusersgroupslectures rename(java.lang.String name) {
		return new sooth.entities.tables.Subscriptionsusersgroupslectures(name, null);
	}
}
