/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subscriptionsassignmentsproblemslecturesgroups extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord> {

	private static final long serialVersionUID = 1674938622;

	/**
	 * The reference instance of <code>asmregen.subscriptionsassignmentsproblemslecturesgroups</code>
	 */
	public static final sooth.entities.tables.Subscriptionsassignmentsproblemslecturesgroups SUBSCRIPTIONSASSIGNMENTSPROBLEMSLECTURESGROUPS = new sooth.entities.tables.Subscriptionsassignmentsproblemslecturesgroups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord> getRecordType() {
		return sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord.class;
	}

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.assignmentId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> ASSIGNMENTID = createField("assignmentId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.problemDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.String> PROBLEMDESCRIPTION = createField("problemDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.pluginDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.String> PLUGINDESCRIPTION = createField("pluginDescription", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.deadline</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.sql.Timestamp> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsassignmentsproblemslecturesgroups.groupType</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord, java.lang.String> GROUPTYPE = createField("groupType", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>asmregen.subscriptionsassignmentsproblemslecturesgroups</code> table reference
	 */
	public Subscriptionsassignmentsproblemslecturesgroups() {
		this("subscriptionsassignmentsproblemslecturesgroups", null);
	}

	/**
	 * Create an aliased <code>asmregen.subscriptionsassignmentsproblemslecturesgroups</code> table reference
	 */
	public Subscriptionsassignmentsproblemslecturesgroups(java.lang.String alias) {
		this(alias, sooth.entities.tables.Subscriptionsassignmentsproblemslecturesgroups.SUBSCRIPTIONSASSIGNMENTSPROBLEMSLECTURESGROUPS);
	}

	private Subscriptionsassignmentsproblemslecturesgroups(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Subscriptionsassignmentsproblemslecturesgroups(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsassignmentsproblemslecturesgroupsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Subscriptionsassignmentsproblemslecturesgroups as(java.lang.String alias) {
		return new sooth.entities.tables.Subscriptionsassignmentsproblemslecturesgroups(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Subscriptionsassignmentsproblemslecturesgroups rename(java.lang.String name) {
		return new sooth.entities.tables.Subscriptionsassignmentsproblemslecturesgroups(name, null);
	}
}
