/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subscriptionsgroupslectures extends org.jooq.impl.TableImpl<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord> {

	private static final long serialVersionUID = 1602612971;

	/**
	 * The reference instance of <code>asmregen.subscriptionsgroupslectures</code>
	 */
	public static final sooth.entities.tables.Subscriptionsgroupslectures SUBSCRIPTIONSGROUPSLECTURES = new sooth.entities.tables.Subscriptionsgroupslectures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord> getRecordType() {
		return sooth.entities.tables.records.SubscriptionsgroupslecturesRecord.class;
	}

	/**
	 * The column <code>asmregen.subscriptionsgroupslectures.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.subscriptionsgroupslectures.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.subscriptionsgroupslectures.status</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsgroupslectures.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsgroupslectures.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsgroupslectures.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.subscriptionsgroupslectures.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.subscriptionsgroupslectures</code> table reference
	 */
	public Subscriptionsgroupslectures() {
		this("subscriptionsgroupslectures", null);
	}

	/**
	 * Create an aliased <code>asmregen.subscriptionsgroupslectures</code> table reference
	 */
	public Subscriptionsgroupslectures(java.lang.String alias) {
		this(alias, sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES);
	}

	private Subscriptionsgroupslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Subscriptionsgroupslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Subscriptionsgroupslectures as(java.lang.String alias) {
		return new sooth.entities.tables.Subscriptionsgroupslectures(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Subscriptionsgroupslectures rename(java.lang.String name) {
		return new sooth.entities.tables.Subscriptionsgroupslectures(name, null);
	}
}
