/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testsplugins extends org.jooq.impl.TableImpl<sooth.entities.tables.records.TestspluginsRecord> {

	private static final long serialVersionUID = -1098039472;

	/**
	 * The reference instance of <code>asmregen.testsplugins</code>
	 */
	public static final sooth.entities.tables.Testsplugins TESTSPLUGINS = new sooth.entities.tables.Testsplugins();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.TestspluginsRecord> getRecordType() {
		return sooth.entities.tables.records.TestspluginsRecord.class;
	}

	/**
	 * The column <code>asmregen.testsplugins.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.testsplugins.description</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.pluginName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> PLUGINNAME = createField("pluginName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.pluginType</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> PLUGINTYPE = createField("pluginType", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.pluginDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> PLUGINDESCRIPTION = createField("pluginDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.pluginFile</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> PLUGINFILE = createField("pluginFile", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.pluginConfig</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> PLUGINCONFIG = createField("pluginConfig", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.config</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> CONFIG = createField("config", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.input</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> INPUT = createField("input", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.status</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.success</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.Integer> SUCCESS = createField("success", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.info</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> INFO = createField("info", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.testsplugins.output</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.TestspluginsRecord, java.lang.String> OUTPUT = createField("output", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>asmregen.testsplugins</code> table reference
	 */
	public Testsplugins() {
		this("testsplugins", null);
	}

	/**
	 * Create an aliased <code>asmregen.testsplugins</code> table reference
	 */
	public Testsplugins(java.lang.String alias) {
		this(alias, sooth.entities.tables.Testsplugins.TESTSPLUGINS);
	}

	private Testsplugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.TestspluginsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Testsplugins(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.TestspluginsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Testsplugins as(java.lang.String alias) {
		return new sooth.entities.tables.Testsplugins(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Testsplugins rename(java.lang.String name) {
		return new sooth.entities.tables.Testsplugins(name, null);
	}
}
