/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uascount extends org.jooq.impl.TableImpl<sooth.entities.tables.records.UascountRecord> {

	private static final long serialVersionUID = -1740390282;

	/**
	 * The reference instance of <code>asmregen.uascount</code>
	 */
	public static final sooth.entities.tables.Uascount UASCOUNT = new sooth.entities.tables.Uascount();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.UascountRecord> getRecordType() {
		return sooth.entities.tables.records.UascountRecord.class;
	}

	/**
	 * The column <code>asmregen.uascount.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UascountRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.uascount.assignmentId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UascountRecord, java.lang.Integer> ASSIGNMENTID = createField("assignmentId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.uascount.submissionsCount</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UascountRecord, java.lang.Long> SUBMISSIONSCOUNT = createField("submissionsCount", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>asmregen.uascount</code> table reference
	 */
	public Uascount() {
		this("uascount", null);
	}

	/**
	 * Create an aliased <code>asmregen.uascount</code> table reference
	 */
	public Uascount(java.lang.String alias) {
		this(alias, sooth.entities.tables.Uascount.UASCOUNT);
	}

	private Uascount(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.UascountRecord> aliased) {
		this(alias, aliased, null);
	}

	private Uascount(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.UascountRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Uascount as(java.lang.String alias) {
		return new sooth.entities.tables.Uascount(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Uascount rename(java.lang.String name) {
		return new sooth.entities.tables.Uascount(name, null);
	}
}
