/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usergroupratingwithowners extends org.jooq.impl.TableImpl<sooth.entities.tables.records.UsergroupratingwithownersRecord> {

	private static final long serialVersionUID = 486942315;

	/**
	 * The reference instance of <code>asmregen.usergroupratingwithowners</code>
	 */
	public static final sooth.entities.tables.Usergroupratingwithowners USERGROUPRATINGWITHOWNERS = new sooth.entities.tables.Usergroupratingwithowners();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.UsergroupratingwithownersRecord> getRecordType() {
		return sooth.entities.tables.records.UsergroupratingwithownersRecord.class;
	}

	/**
	 * The column <code>asmregen.usergroupratingwithowners.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.realName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.String> REALNAME = createField("realName", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.email</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.rating</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.math.BigInteger> RATING = createField("rating", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(32), this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergroupratingwithowners.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingwithownersRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.usergroupratingwithowners</code> table reference
	 */
	public Usergroupratingwithowners() {
		this("usergroupratingwithowners", null);
	}

	/**
	 * Create an aliased <code>asmregen.usergroupratingwithowners</code> table reference
	 */
	public Usergroupratingwithowners(java.lang.String alias) {
		this(alias, sooth.entities.tables.Usergroupratingwithowners.USERGROUPRATINGWITHOWNERS);
	}

	private Usergroupratingwithowners(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.UsergroupratingwithownersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Usergroupratingwithowners(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.UsergroupratingwithownersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Usergroupratingwithowners as(java.lang.String alias) {
		return new sooth.entities.tables.Usergroupratingwithowners(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Usergroupratingwithowners rename(java.lang.String name) {
		return new sooth.entities.tables.Usergroupratingwithowners(name, null);
	}
}
