/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usergrouprating extends org.jooq.impl.TableImpl<sooth.entities.tables.records.UsergroupratingRecord> {

	private static final long serialVersionUID = 290306711;

	/**
	 * The reference instance of <code>asmregen.usergrouprating</code>
	 */
	public static final sooth.entities.tables.Usergrouprating USERGROUPRATING = new sooth.entities.tables.Usergrouprating();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.UsergroupratingRecord> getRecordType() {
		return sooth.entities.tables.records.UsergroupratingRecord.class;
	}

	/**
	 * The column <code>asmregen.usergrouprating.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.usergrouprating.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergrouprating.realName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.String> REALNAME = createField("realName", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergrouprating.email</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergrouprating.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.usergrouprating.rating</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.math.BigInteger> RATING = createField("rating", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(32), this, "");

	/**
	 * The column <code>asmregen.usergrouprating.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergrouprating.groupDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.String> GROUPDESCRIPTION = createField("groupDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergrouprating.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.usergrouprating.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UsergroupratingRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>asmregen.usergrouprating</code> table reference
	 */
	public Usergrouprating() {
		this("usergrouprating", null);
	}

	/**
	 * Create an aliased <code>asmregen.usergrouprating</code> table reference
	 */
	public Usergrouprating(java.lang.String alias) {
		this(alias, sooth.entities.tables.Usergrouprating.USERGROUPRATING);
	}

	private Usergrouprating(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.UsergroupratingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Usergrouprating(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.UsergroupratingRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Usergrouprating as(java.lang.String alias) {
		return new sooth.entities.tables.Usergrouprating(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Usergrouprating rename(java.lang.String name) {
		return new sooth.entities.tables.Usergrouprating(name, null);
	}
}
