/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userssubmissionsconfirmedwithowners extends org.jooq.impl.TableImpl<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord> {

	private static final long serialVersionUID = -1477272035;

	/**
	 * The reference instance of <code>asmregen.userssubmissionsconfirmedwithowners</code>
	 */
	public static final sooth.entities.tables.Userssubmissionsconfirmedwithowners USERSSUBMISSIONSCONFIRMEDWITHOWNERS = new sooth.entities.tables.Userssubmissionsconfirmedwithowners();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord> getRecordType() {
		return sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord.class;
	}

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.userId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.name</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.realName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.String> REALNAME = createField("realName", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.email</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.groupId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.Integer> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.assignmentId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.Integer> ASSIGNMENTID = createField("assignmentId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.submissionId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.Integer> SUBMISSIONID = createField("submissionId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.rating</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.String> RATING = createField("rating", org.jooq.impl.SQLDataType.VARCHAR.length(11).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.explanation</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.String> EXPLANATION = createField("explanation", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.reward</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.Integer> REWARD = createField("reward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.problemName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.String> PROBLEMNAME = createField("problemName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.groupName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.String> GROUPNAME = createField("groupName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.userssubmissionsconfirmedwithowners.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>asmregen.userssubmissionsconfirmedwithowners</code> table reference
	 */
	public Userssubmissionsconfirmedwithowners() {
		this("userssubmissionsconfirmedwithowners", null);
	}

	/**
	 * Create an aliased <code>asmregen.userssubmissionsconfirmedwithowners</code> table reference
	 */
	public Userssubmissionsconfirmedwithowners(java.lang.String alias) {
		this(alias, sooth.entities.tables.Userssubmissionsconfirmedwithowners.USERSSUBMISSIONSCONFIRMEDWITHOWNERS);
	}

	private Userssubmissionsconfirmedwithowners(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Userssubmissionsconfirmedwithowners(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.UserssubmissionsconfirmedwithownersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Userssubmissionsconfirmedwithowners as(java.lang.String alias) {
		return new sooth.entities.tables.Userssubmissionsconfirmedwithowners(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Userssubmissionsconfirmedwithowners rename(java.lang.String name) {
		return new sooth.entities.tables.Userssubmissionsconfirmedwithowners(name, null);
	}
}
