/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Xtestslectures extends org.jooq.impl.TableImpl<sooth.entities.tables.records.XtestslecturesRecord> {

	private static final long serialVersionUID = 194089498;

	/**
	 * The reference instance of <code>asmregen.xtestslectures</code>
	 */
	public static final sooth.entities.tables.Xtestslectures XTESTSLECTURES = new sooth.entities.tables.Xtestslectures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<sooth.entities.tables.records.XtestslecturesRecord> getRecordType() {
		return sooth.entities.tables.records.XtestslecturesRecord.class;
	}

	/**
	 * The column <code>asmregen.xtestslectures.id</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>asmregen.xtestslectures.description</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>asmregen.xtestslectures.template</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.String> TEMPLATE = createField("template", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.xtestslectures.count</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.Integer> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>asmregen.xtestslectures.generated</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.String> GENERATED = createField("generated", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.xtestslectures.lectureId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.Integer> LECTUREID = createField("lectureId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>asmregen.xtestslectures.lectureName</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.String> LECTURENAME = createField("lectureName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>asmregen.xtestslectures.lectureDescription</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.String> LECTUREDESCRIPTION = createField("lectureDescription", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>asmregen.xtestslectures.ownerId</code>.
	 */
	public final org.jooq.TableField<sooth.entities.tables.records.XtestslecturesRecord, java.lang.Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>asmregen.xtestslectures</code> table reference
	 */
	public Xtestslectures() {
		this("xtestslectures", null);
	}

	/**
	 * Create an aliased <code>asmregen.xtestslectures</code> table reference
	 */
	public Xtestslectures(java.lang.String alias) {
		this(alias, sooth.entities.tables.Xtestslectures.XTESTSLECTURES);
	}

	private Xtestslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.XtestslecturesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Xtestslectures(java.lang.String alias, org.jooq.Table<sooth.entities.tables.records.XtestslecturesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, sooth.entities.Asmregen.ASMREGEN, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public sooth.entities.tables.Xtestslectures as(java.lang.String alias) {
		return new sooth.entities.tables.Xtestslectures(alias, this);
	}

	/**
	 * Rename this table
	 */
	public sooth.entities.tables.Xtestslectures rename(java.lang.String name) {
		return new sooth.entities.tables.Xtestslectures(name, null);
	}
}
