/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentsproblemslecturesRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.AssignmentsproblemslecturesRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 2029845957;

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.problemId</code>.
	 */
	public void setProblemid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.problemId</code>.
	 */
	public java.lang.Integer getProblemid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.problemName</code>.
	 */
	public void setProblemname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.problemName</code>.
	 */
	public java.lang.String getProblemname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.problemDescription</code>.
	 */
	public void setProblemdescription(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.problemDescription</code>.
	 */
	public java.lang.String getProblemdescription() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.deadline</code>.
	 */
	public void setDeadline(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.deadline</code>.
	 */
	public java.sql.Timestamp getDeadline() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.reward</code>.
	 */
	public void setReward(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.reward</code>.
	 */
	public java.lang.Integer getReward() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.lectureDescription</code>.
	 */
	public void setLecturedescription(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.lectureDescription</code>.
	 */
	public java.lang.String getLecturedescription() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.groupId</code>.
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.groupId</code>.
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslectures.pluginId</code>.
	 */
	public void setPluginid(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslectures.pluginId</code>.
	 */
	public java.lang.Integer getPluginid() {
		return (java.lang.Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.PROBLEMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.PROBLEMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.PROBLEMDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.DEADLINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.REWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.LECTUREDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES.PLUGINID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getProblemid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getProblemname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getProblemdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getDeadline();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getReward();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getLecturedescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getPluginid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value2(java.lang.Integer value) {
		setProblemid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value3(java.lang.String value) {
		setProblemname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value4(java.lang.String value) {
		setProblemdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value5(java.sql.Timestamp value) {
		setDeadline(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value6(java.lang.Integer value) {
		setReward(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value7(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value8(java.lang.String value) {
		setLecturedescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value9(java.lang.Integer value) {
		setGroupid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord value10(java.lang.Integer value) {
		setPluginid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.sql.Timestamp value5, java.lang.Integer value6, java.lang.String value7, java.lang.String value8, java.lang.Integer value9, java.lang.Integer value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AssignmentsproblemslecturesRecord
	 */
	public AssignmentsproblemslecturesRecord() {
		super(sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES);
	}

	/**
	 * Create a detached, initialised AssignmentsproblemslecturesRecord
	 */
	public AssignmentsproblemslecturesRecord(java.lang.Integer id, java.lang.Integer problemid, java.lang.String problemname, java.lang.String problemdescription, java.sql.Timestamp deadline, java.lang.Integer reward, java.lang.String lecturename, java.lang.String lecturedescription, java.lang.Integer groupid, java.lang.Integer pluginid) {
		super(sooth.entities.tables.Assignmentsproblemslectures.ASSIGNMENTSPROBLEMSLECTURES);

		setValue(0, id);
		setValue(1, problemid);
		setValue(2, problemname);
		setValue(3, problemdescription);
		setValue(4, deadline);
		setValue(5, reward);
		setValue(6, lecturename);
		setValue(7, lecturedescription);
		setValue(8, groupid);
		setValue(9, pluginid);
	}
}
