/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentsproblemslecturesgroupspluginsRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.AssignmentsproblemslecturesgroupspluginsRecord> implements org.jooq.Record14<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -90970390;

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemId</code>.
	 */
	public void setProblemid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemId</code>.
	 */
	public java.lang.Integer getProblemid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemName</code>.
	 */
	public void setProblemname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemName</code>.
	 */
	public java.lang.String getProblemname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemDescription</code>.
	 */
	public void setProblemdescription(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.problemDescription</code>.
	 */
	public java.lang.String getProblemdescription() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.pluginDescription</code>.
	 */
	public void setPlugindescription(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.pluginDescription</code>.
	 */
	public java.lang.String getPlugindescription() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.deadline</code>.
	 */
	public void setDeadline(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.deadline</code>.
	 */
	public java.sql.Timestamp getDeadline() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.reward</code>.
	 */
	public void setReward(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.reward</code>.
	 */
	public java.lang.Integer getReward() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.lectureDescription</code>.
	 */
	public void setLecturedescription(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.lectureDescription</code>.
	 */
	public java.lang.String getLecturedescription() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupName</code>.
	 */
	public void setGroupname(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupName</code>.
	 */
	public java.lang.String getGroupname() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupDescription</code>.
	 */
	public void setGroupdescription(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupDescription</code>.
	 */
	public java.lang.String getGroupdescription() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.ownerId</code>.
	 */
	public void setOwnerid(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.ownerId</code>.
	 */
	public java.lang.Integer getOwnerid() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupType</code>.
	 */
	public void setGrouptype(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupType</code>.
	 */
	public java.lang.String getGrouptype() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupId</code>.
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>asmregen.assignmentsproblemslecturesgroupsplugins.groupId</code>.
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.PROBLEMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.PROBLEMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.PROBLEMDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.PLUGINDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.DEADLINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.REWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.LECTUREDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.GROUPNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.GROUPDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.OWNERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.GROUPTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field14() {
		return sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getProblemid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getProblemname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getProblemdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPlugindescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getDeadline();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getReward();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getLecturedescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getGroupname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getGroupdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getOwnerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getGrouptype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value14() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value2(java.lang.Integer value) {
		setProblemid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value3(java.lang.String value) {
		setProblemname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value4(java.lang.String value) {
		setProblemdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value5(java.lang.String value) {
		setPlugindescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value6(java.sql.Timestamp value) {
		setDeadline(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value7(java.lang.Integer value) {
		setReward(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value8(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value9(java.lang.String value) {
		setLecturedescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value10(java.lang.String value) {
		setGroupname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value11(java.lang.String value) {
		setGroupdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value12(java.lang.Integer value) {
		setOwnerid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value13(java.lang.String value) {
		setGrouptype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord value14(java.lang.Integer value) {
		setGroupid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssignmentsproblemslecturesgroupspluginsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.sql.Timestamp value6, java.lang.Integer value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11, java.lang.Integer value12, java.lang.String value13, java.lang.Integer value14) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AssignmentsproblemslecturesgroupspluginsRecord
	 */
	public AssignmentsproblemslecturesgroupspluginsRecord() {
		super(sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS);
	}

	/**
	 * Create a detached, initialised AssignmentsproblemslecturesgroupspluginsRecord
	 */
	public AssignmentsproblemslecturesgroupspluginsRecord(java.lang.Integer id, java.lang.Integer problemid, java.lang.String problemname, java.lang.String problemdescription, java.lang.String plugindescription, java.sql.Timestamp deadline, java.lang.Integer reward, java.lang.String lecturename, java.lang.String lecturedescription, java.lang.String groupname, java.lang.String groupdescription, java.lang.Integer ownerid, java.lang.String grouptype, java.lang.Integer groupid) {
		super(sooth.entities.tables.Assignmentsproblemslecturesgroupsplugins.ASSIGNMENTSPROBLEMSLECTURESGROUPSPLUGINS);

		setValue(0, id);
		setValue(1, problemid);
		setValue(2, problemname);
		setValue(3, problemdescription);
		setValue(4, plugindescription);
		setValue(5, deadline);
		setValue(6, reward);
		setValue(7, lecturename);
		setValue(8, lecturedescription);
		setValue(9, groupname);
		setValue(10, groupdescription);
		setValue(11, ownerid);
		setValue(12, grouptype);
		setValue(13, groupid);
	}
}
