/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttachmentslecturesRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.AttachmentslecturesRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 82397497;

	/**
	 * Setter for <code>asmregen.attachmentslectures.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.attachmentslectures.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.attachmentslectures.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.attachmentslectures.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.attachmentslectures.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.attachmentslectures.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.attachmentslectures.file</code>.
	 */
	public void setFile(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.attachmentslectures.file</code>.
	 */
	public java.lang.String getFile() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.attachmentslectures.lectureId</code>.
	 */
	public void setLectureid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.attachmentslectures.lectureId</code>.
	 */
	public java.lang.Integer getLectureid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.attachmentslectures.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.attachmentslectures.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.attachmentslectures.lectureDescription</code>.
	 */
	public void setLecturedescription(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.attachmentslectures.lectureDescription</code>.
	 */
	public java.lang.String getLecturedescription() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.attachmentslectures.ownerId</code>.
	 */
	public void setOwnerid(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.attachmentslectures.ownerId</code>.
	 */
	public java.lang.Integer getOwnerid() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES.FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES.LECTUREID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES.LECTUREDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES.OWNERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getLectureid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getLecturedescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getOwnerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord value3(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord value4(java.lang.String value) {
		setFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord value5(java.lang.Integer value) {
		setLectureid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord value6(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord value7(java.lang.String value) {
		setLecturedescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord value8(java.lang.Integer value) {
		setOwnerid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachmentslecturesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.String value6, java.lang.String value7, java.lang.Integer value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AttachmentslecturesRecord
	 */
	public AttachmentslecturesRecord() {
		super(sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES);
	}

	/**
	 * Create a detached, initialised AttachmentslecturesRecord
	 */
	public AttachmentslecturesRecord(java.lang.Integer id, java.lang.String name, java.lang.String type, java.lang.String file, java.lang.Integer lectureid, java.lang.String lecturename, java.lang.String lecturedescription, java.lang.Integer ownerid) {
		super(sooth.entities.tables.Attachmentslectures.ATTACHMENTSLECTURES);

		setValue(0, id);
		setValue(1, name);
		setValue(2, type);
		setValue(3, file);
		setValue(4, lectureid);
		setValue(5, lecturename);
		setValue(6, lecturedescription);
		setValue(7, ownerid);
	}
}
