/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProblemspluginsRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.ProblemspluginsRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1159700990;

	/**
	 * Setter for <code>asmregen.problemsplugins.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.problemsplugins.problemName</code>.
	 */
	public void setProblemname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.problemName</code>.
	 */
	public java.lang.String getProblemname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.problemsplugins.problemDescription</code>.
	 */
	public void setProblemdescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.problemDescription</code>.
	 */
	public java.lang.String getProblemdescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.problemsplugins.problemConfig</code>.
	 */
	public void setProblemconfig(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.problemConfig</code>.
	 */
	public java.lang.String getProblemconfig() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.problemsplugins.pluginName</code>.
	 */
	public void setPluginname(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.pluginName</code>.
	 */
	public java.lang.String getPluginname() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.problemsplugins.pluginType</code>.
	 */
	public void setPlugintype(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.pluginType</code>.
	 */
	public java.lang.String getPlugintype() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.problemsplugins.pluginDescription</code>.
	 */
	public void setPlugindescription(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.pluginDescription</code>.
	 */
	public java.lang.String getPlugindescription() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.problemsplugins.pluginMainFile</code>.
	 */
	public void setPluginmainfile(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.pluginMainFile</code>.
	 */
	public java.lang.String getPluginmainfile() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.problemsplugins.pluginConfig</code>.
	 */
	public void setPluginconfig(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.problemsplugins.pluginConfig</code>.
	 */
	public java.lang.String getPluginconfig() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.PROBLEMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.PROBLEMDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.PROBLEMCONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.PLUGINNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.PLUGINTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.PLUGINDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.PLUGINMAINFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS.PLUGINCONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getProblemname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getProblemdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getProblemconfig();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPluginname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getPlugintype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getPlugindescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getPluginmainfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getPluginconfig();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value2(java.lang.String value) {
		setProblemname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value3(java.lang.String value) {
		setProblemdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value4(java.lang.String value) {
		setProblemconfig(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value5(java.lang.String value) {
		setPluginname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value6(java.lang.String value) {
		setPlugintype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value7(java.lang.String value) {
		setPlugindescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value8(java.lang.String value) {
		setPluginmainfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord value9(java.lang.String value) {
		setPluginconfig(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProblemspluginsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProblemspluginsRecord
	 */
	public ProblemspluginsRecord() {
		super(sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS);
	}

	/**
	 * Create a detached, initialised ProblemspluginsRecord
	 */
	public ProblemspluginsRecord(java.lang.Integer id, java.lang.String problemname, java.lang.String problemdescription, java.lang.String problemconfig, java.lang.String pluginname, java.lang.String plugintype, java.lang.String plugindescription, java.lang.String pluginmainfile, java.lang.String pluginconfig) {
		super(sooth.entities.tables.Problemsplugins.PROBLEMSPLUGINS);

		setValue(0, id);
		setValue(1, problemname);
		setValue(2, problemdescription);
		setValue(3, problemconfig);
		setValue(4, pluginname);
		setValue(5, plugintype);
		setValue(6, plugindescription);
		setValue(7, pluginmainfile);
		setValue(8, pluginconfig);
	}
}
