/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubmissionsassignmentsproblemslecturesgroupsRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.SubmissionsassignmentsproblemslecturesgroupsRecord> implements org.jooq.Record20<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 489910789;

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.assignmentId</code>.
	 */
	public void setAssignmentid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.assignmentId</code>.
	 */
	public java.lang.Integer getAssignmentid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupId</code>.
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupId</code>.
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.userId</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.userId</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.submissionFile</code>.
	 */
	public void setSubmissionfile(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.submissionFile</code>.
	 */
	public java.lang.String getSubmissionfile() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.date</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.date</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.success</code>.
	 */
	public void setSuccess(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.success</code>.
	 */
	public java.lang.Integer getSuccess() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.info</code>.
	 */
	public void setInfo(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.info</code>.
	 */
	public java.lang.String getInfo() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.outputFile</code>.
	 */
	public void setOutputfile(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.outputFile</code>.
	 */
	public java.lang.String getOutputfile() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.rating</code>.
	 */
	public void setRating(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.rating</code>.
	 */
	public java.lang.Integer getRating() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.explanation</code>.
	 */
	public void setExplanation(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.explanation</code>.
	 */
	public java.lang.String getExplanation() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.problemName</code>.
	 */
	public void setProblemname(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.problemName</code>.
	 */
	public java.lang.String getProblemname() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.problemDescription</code>.
	 */
	public void setProblemdescription(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.problemDescription</code>.
	 */
	public java.lang.String getProblemdescription() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.deadline</code>.
	 */
	public void setDeadline(java.sql.Timestamp value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.deadline</code>.
	 */
	public java.sql.Timestamp getDeadline() {
		return (java.sql.Timestamp) getValue(14);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.reward</code>.
	 */
	public void setReward(java.lang.Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.reward</code>.
	 */
	public java.lang.Integer getReward() {
		return (java.lang.Integer) getValue(15);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.lectureDescription</code>.
	 */
	public void setLecturedescription(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.lectureDescription</code>.
	 */
	public java.lang.String getLecturedescription() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupName</code>.
	 */
	public void setGroupname(java.lang.String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupName</code>.
	 */
	public java.lang.String getGroupname() {
		return (java.lang.String) getValue(18);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupDescription</code>.
	 */
	public void setGroupdescription(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemslecturesgroups.groupDescription</code>.
	 */
	public java.lang.String getGroupdescription() {
		return (java.lang.String) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.ASSIGNMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.SUBMISSIONFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.SUCCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.OUTPUTFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.EXPLANATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.PROBLEMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.PROBLEMDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field15() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.DEADLINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field16() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.REWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field17() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field18() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.LECTUREDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field19() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.GROUPNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field20() {
		return sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS.GROUPDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAssignmentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSubmissionfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getSuccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getOutputfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getExplanation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getProblemname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getProblemdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value15() {
		return getDeadline();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value16() {
		return getReward();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value17() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value18() {
		return getLecturedescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value19() {
		return getGroupname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value20() {
		return getGroupdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value2(java.lang.Integer value) {
		setAssignmentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value3(java.lang.Integer value) {
		setGroupid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value4(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value5(java.lang.String value) {
		setSubmissionfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value6(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value7(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value8(java.lang.Integer value) {
		setSuccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value9(java.lang.String value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value10(java.lang.String value) {
		setOutputfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value11(java.lang.Integer value) {
		setRating(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value12(java.lang.String value) {
		setExplanation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value13(java.lang.String value) {
		setProblemname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value14(java.lang.String value) {
		setProblemdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value15(java.sql.Timestamp value) {
		setDeadline(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value16(java.lang.Integer value) {
		setReward(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value17(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value18(java.lang.String value) {
		setLecturedescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value19(java.lang.String value) {
		setGroupname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord value20(java.lang.String value) {
		setGroupdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemslecturesgroupsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.String value5, java.sql.Timestamp value6, java.lang.String value7, java.lang.Integer value8, java.lang.String value9, java.lang.String value10, java.lang.Integer value11, java.lang.String value12, java.lang.String value13, java.lang.String value14, java.sql.Timestamp value15, java.lang.Integer value16, java.lang.String value17, java.lang.String value18, java.lang.String value19, java.lang.String value20) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubmissionsassignmentsproblemslecturesgroupsRecord
	 */
	public SubmissionsassignmentsproblemslecturesgroupsRecord() {
		super(sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS);
	}

	/**
	 * Create a detached, initialised SubmissionsassignmentsproblemslecturesgroupsRecord
	 */
	public SubmissionsassignmentsproblemslecturesgroupsRecord(java.lang.Integer id, java.lang.Integer assignmentid, java.lang.Integer groupid, java.lang.Integer userid, java.lang.String submissionfile, java.sql.Timestamp date, java.lang.String status, java.lang.Integer success, java.lang.String info, java.lang.String outputfile, java.lang.Integer rating, java.lang.String explanation, java.lang.String problemname, java.lang.String problemdescription, java.sql.Timestamp deadline, java.lang.Integer reward, java.lang.String lecturename, java.lang.String lecturedescription, java.lang.String groupname, java.lang.String groupdescription) {
		super(sooth.entities.tables.Submissionsassignmentsproblemslecturesgroups.SUBMISSIONSASSIGNMENTSPROBLEMSLECTURESGROUPS);

		setValue(0, id);
		setValue(1, assignmentid);
		setValue(2, groupid);
		setValue(3, userid);
		setValue(4, submissionfile);
		setValue(5, date);
		setValue(6, status);
		setValue(7, success);
		setValue(8, info);
		setValue(9, outputfile);
		setValue(10, rating);
		setValue(11, explanation);
		setValue(12, problemname);
		setValue(13, problemdescription);
		setValue(14, deadline);
		setValue(15, reward);
		setValue(16, lecturename);
		setValue(17, lecturedescription);
		setValue(18, groupname);
		setValue(19, groupdescription);
	}
}
