/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubmissionsusersRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.SubmissionsusersRecord> implements org.jooq.Record12<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1872682208;

	/**
	 * Setter for <code>asmregen.submissionsusers.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.assignmentId</code>.
	 */
	public void setAssignmentid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.assignmentId</code>.
	 */
	public java.lang.Integer getAssignmentid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.userId</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.userId</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.realName</code>.
	 */
	public void setRealname(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.realName</code>.
	 */
	public java.lang.String getRealname() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.submissionFile</code>.
	 */
	public void setSubmissionfile(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.submissionFile</code>.
	 */
	public java.lang.String getSubmissionfile() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.date</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.date</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.success</code>.
	 */
	public void setSuccess(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.success</code>.
	 */
	public java.lang.Integer getSuccess() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.info</code>.
	 */
	public void setInfo(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.info</code>.
	 */
	public java.lang.String getInfo() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.outputFile</code>.
	 */
	public void setOutputfile(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.outputFile</code>.
	 */
	public java.lang.String getOutputfile() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.rating</code>.
	 */
	public void setRating(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.rating</code>.
	 */
	public java.lang.Integer getRating() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>asmregen.submissionsusers.explanation</code>.
	 */
	public void setExplanation(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsusers.explanation</code>.
	 */
	public java.lang.String getExplanation() {
		return (java.lang.String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.ASSIGNMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.REALNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.SUBMISSIONFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.SUCCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.OUTPUTFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS.EXPLANATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAssignmentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getRealname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSubmissionfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getSuccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getOutputfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getExplanation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value2(java.lang.Integer value) {
		setAssignmentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value3(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value4(java.lang.String value) {
		setRealname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value5(java.lang.String value) {
		setSubmissionfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value6(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value7(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value8(java.lang.Integer value) {
		setSuccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value9(java.lang.String value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value10(java.lang.String value) {
		setOutputfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value11(java.lang.Integer value) {
		setRating(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord value12(java.lang.String value) {
		setExplanation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsusersRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.String value4, java.lang.String value5, java.sql.Timestamp value6, java.lang.String value7, java.lang.Integer value8, java.lang.String value9, java.lang.String value10, java.lang.Integer value11, java.lang.String value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubmissionsusersRecord
	 */
	public SubmissionsusersRecord() {
		super(sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS);
	}

	/**
	 * Create a detached, initialised SubmissionsusersRecord
	 */
	public SubmissionsusersRecord(java.lang.Integer id, java.lang.Integer assignmentid, java.lang.Integer userid, java.lang.String realname, java.lang.String submissionfile, java.sql.Timestamp date, java.lang.String status, java.lang.Integer success, java.lang.String info, java.lang.String outputfile, java.lang.Integer rating, java.lang.String explanation) {
		super(sooth.entities.tables.Submissionsusers.SUBMISSIONSUSERS);

		setValue(0, id);
		setValue(1, assignmentid);
		setValue(2, userid);
		setValue(3, realname);
		setValue(4, submissionfile);
		setValue(5, date);
		setValue(6, status);
		setValue(7, success);
		setValue(8, info);
		setValue(9, outputfile);
		setValue(10, rating);
		setValue(11, explanation);
	}
}
