/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubmissionsassignmentsproblemspluginsRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.SubmissionsassignmentsproblemspluginsRecord> implements org.jooq.Record21<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -60419910;

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.userId</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.userId</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.submissionFile</code>.
	 */
	public void setSubmissionfile(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.submissionFile</code>.
	 */
	public java.lang.String getSubmissionfile() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.date</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.date</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.success</code>.
	 */
	public void setSuccess(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.success</code>.
	 */
	public java.lang.Integer getSuccess() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.info</code>.
	 */
	public void setInfo(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.info</code>.
	 */
	public java.lang.String getInfo() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.outputFile</code>.
	 */
	public void setOutputfile(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.outputFile</code>.
	 */
	public java.lang.String getOutputfile() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.rating</code>.
	 */
	public void setRating(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.rating</code>.
	 */
	public java.lang.Integer getRating() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.explanation</code>.
	 */
	public void setExplanation(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.explanation</code>.
	 */
	public java.lang.String getExplanation() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.deadline</code>.
	 */
	public void setDeadline(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.deadline</code>.
	 */
	public java.sql.Timestamp getDeadline() {
		return (java.sql.Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.reward</code>.
	 */
	public void setReward(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.reward</code>.
	 */
	public java.lang.Integer getReward() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.groupId</code>.
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.groupId</code>.
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(12);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.problemName</code>.
	 */
	public void setProblemname(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.problemName</code>.
	 */
	public java.lang.String getProblemname() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.problemDescription</code>.
	 */
	public void setProblemdescription(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.problemDescription</code>.
	 */
	public java.lang.String getProblemdescription() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.problemConfig</code>.
	 */
	public void setProblemconfig(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.problemConfig</code>.
	 */
	public java.lang.String getProblemconfig() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginName</code>.
	 */
	public void setPluginname(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginName</code>.
	 */
	public java.lang.String getPluginname() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginType</code>.
	 */
	public void setPlugintype(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginType</code>.
	 */
	public java.lang.String getPlugintype() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginDescription</code>.
	 */
	public void setPlugindescription(java.lang.String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginDescription</code>.
	 */
	public java.lang.String getPlugindescription() {
		return (java.lang.String) getValue(18);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginMainFile</code>.
	 */
	public void setPluginmainfile(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginMainFile</code>.
	 */
	public java.lang.String getPluginmainfile() {
		return (java.lang.String) getValue(19);
	}

	/**
	 * Setter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginConfig</code>.
	 */
	public void setPluginconfig(java.lang.String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsassignmentsproblemsplugins.pluginConfig</code>.
	 */
	public java.lang.String getPluginconfig() {
		return (java.lang.String) getValue(20);
	}

	// -------------------------------------------------------------------------
	// Record21 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row21<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row21) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row21<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row21) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.SUBMISSIONFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.SUCCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.OUTPUTFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.EXPLANATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.DEADLINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.REWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field13() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.PROBLEMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.PROBLEMDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.PROBLEMCONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field17() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.PLUGINNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field18() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.PLUGINTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field19() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.PLUGINDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field20() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.PLUGINMAINFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field21() {
		return sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS.PLUGINCONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSubmissionfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getSuccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getOutputfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getExplanation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getDeadline();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getReward();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value13() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getProblemname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getProblemdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getProblemconfig();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value17() {
		return getPluginname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value18() {
		return getPlugintype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value19() {
		return getPlugindescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value20() {
		return getPluginmainfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value21() {
		return getPluginconfig();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value2(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value3(java.lang.String value) {
		setSubmissionfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value4(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value5(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value6(java.lang.Integer value) {
		setSuccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value7(java.lang.String value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value8(java.lang.String value) {
		setOutputfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value9(java.lang.Integer value) {
		setRating(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value10(java.lang.String value) {
		setExplanation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value11(java.sql.Timestamp value) {
		setDeadline(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value12(java.lang.Integer value) {
		setReward(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value13(java.lang.Integer value) {
		setGroupid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value14(java.lang.String value) {
		setProblemname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value15(java.lang.String value) {
		setProblemdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value16(java.lang.String value) {
		setProblemconfig(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value17(java.lang.String value) {
		setPluginname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value18(java.lang.String value) {
		setPlugintype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value19(java.lang.String value) {
		setPlugindescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value20(java.lang.String value) {
		setPluginmainfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord value21(java.lang.String value) {
		setPluginconfig(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsassignmentsproblemspluginsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.String value5, java.lang.Integer value6, java.lang.String value7, java.lang.String value8, java.lang.Integer value9, java.lang.String value10, java.sql.Timestamp value11, java.lang.Integer value12, java.lang.Integer value13, java.lang.String value14, java.lang.String value15, java.lang.String value16, java.lang.String value17, java.lang.String value18, java.lang.String value19, java.lang.String value20, java.lang.String value21) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubmissionsassignmentsproblemspluginsRecord
	 */
	public SubmissionsassignmentsproblemspluginsRecord() {
		super(sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS);
	}

	/**
	 * Create a detached, initialised SubmissionsassignmentsproblemspluginsRecord
	 */
	public SubmissionsassignmentsproblemspluginsRecord(java.lang.Integer id, java.lang.Integer userid, java.lang.String submissionfile, java.sql.Timestamp date, java.lang.String status, java.lang.Integer success, java.lang.String info, java.lang.String outputfile, java.lang.Integer rating, java.lang.String explanation, java.sql.Timestamp deadline, java.lang.Integer reward, java.lang.Integer groupid, java.lang.String problemname, java.lang.String problemdescription, java.lang.String problemconfig, java.lang.String pluginname, java.lang.String plugintype, java.lang.String plugindescription, java.lang.String pluginmainfile, java.lang.String pluginconfig) {
		super(sooth.entities.tables.Submissionsassignmentsproblemsplugins.SUBMISSIONSASSIGNMENTSPROBLEMSPLUGINS);

		setValue(0, id);
		setValue(1, userid);
		setValue(2, submissionfile);
		setValue(3, date);
		setValue(4, status);
		setValue(5, success);
		setValue(6, info);
		setValue(7, outputfile);
		setValue(8, rating);
		setValue(9, explanation);
		setValue(10, deadline);
		setValue(11, reward);
		setValue(12, groupid);
		setValue(13, problemname);
		setValue(14, problemdescription);
		setValue(15, problemconfig);
		setValue(16, pluginname);
		setValue(17, plugintype);
		setValue(18, plugindescription);
		setValue(19, pluginmainfile);
		setValue(20, pluginconfig);
	}
}
