/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubmissionsfullwithownersRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.SubmissionsfullwithownersRecord> implements org.jooq.Record22<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1191921932;

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.assignmentId</code>.
	 */
	public void setAssignmentid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.assignmentId</code>.
	 */
	public java.lang.Integer getAssignmentid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.groupId</code>.
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.groupId</code>.
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.userId</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.userId</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.ownerId</code>.
	 */
	public void setOwnerid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.ownerId</code>.
	 */
	public java.lang.Integer getOwnerid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.submissionFile</code>.
	 */
	public void setSubmissionfile(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.submissionFile</code>.
	 */
	public java.lang.String getSubmissionfile() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.date</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.date</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.success</code>.
	 */
	public void setSuccess(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.success</code>.
	 */
	public java.lang.Integer getSuccess() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.info</code>.
	 */
	public void setInfo(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.info</code>.
	 */
	public java.lang.String getInfo() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.outputFile</code>.
	 */
	public void setOutputfile(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.outputFile</code>.
	 */
	public java.lang.String getOutputfile() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.rating</code>.
	 */
	public void setRating(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.rating</code>.
	 */
	public java.lang.Integer getRating() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.explanation</code>.
	 */
	public void setExplanation(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.explanation</code>.
	 */
	public java.lang.String getExplanation() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.problemName</code>.
	 */
	public void setProblemname(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.problemName</code>.
	 */
	public java.lang.String getProblemname() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.problemDescription</code>.
	 */
	public void setProblemdescription(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.problemDescription</code>.
	 */
	public java.lang.String getProblemdescription() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.deadline</code>.
	 */
	public void setDeadline(java.sql.Timestamp value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.deadline</code>.
	 */
	public java.sql.Timestamp getDeadline() {
		return (java.sql.Timestamp) getValue(15);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.reward</code>.
	 */
	public void setReward(java.lang.Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.reward</code>.
	 */
	public java.lang.Integer getReward() {
		return (java.lang.Integer) getValue(16);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.lectureDescription</code>.
	 */
	public void setLecturedescription(java.lang.String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.lectureDescription</code>.
	 */
	public java.lang.String getLecturedescription() {
		return (java.lang.String) getValue(18);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.groupName</code>.
	 */
	public void setGroupname(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.groupName</code>.
	 */
	public java.lang.String getGroupname() {
		return (java.lang.String) getValue(19);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.groupDescription</code>.
	 */
	public void setGroupdescription(java.lang.String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.groupDescription</code>.
	 */
	public java.lang.String getGroupdescription() {
		return (java.lang.String) getValue(20);
	}

	/**
	 * Setter for <code>asmregen.submissionsfullwithowners.realName</code>.
	 */
	public void setRealname(java.lang.String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>asmregen.submissionsfullwithowners.realName</code>.
	 */
	public java.lang.String getRealname() {
		return (java.lang.String) getValue(21);
	}

	// -------------------------------------------------------------------------
	// Record22 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row22) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row22) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.ASSIGNMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.OWNERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.SUBMISSIONFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.SUCCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.OUTPUTFILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.EXPLANATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.PROBLEMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.PROBLEMDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field16() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.DEADLINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field17() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.REWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field18() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field19() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.LECTUREDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field20() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.GROUPNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field21() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.GROUPDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field22() {
		return sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS.REALNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAssignmentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getOwnerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSubmissionfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getSuccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getOutputfile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getExplanation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getProblemname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getProblemdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value16() {
		return getDeadline();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value17() {
		return getReward();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value18() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value19() {
		return getLecturedescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value20() {
		return getGroupname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value21() {
		return getGroupdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value22() {
		return getRealname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value2(java.lang.Integer value) {
		setAssignmentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value3(java.lang.Integer value) {
		setGroupid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value4(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value5(java.lang.Integer value) {
		setOwnerid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value6(java.lang.String value) {
		setSubmissionfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value7(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value8(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value9(java.lang.Integer value) {
		setSuccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value10(java.lang.String value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value11(java.lang.String value) {
		setOutputfile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value12(java.lang.Integer value) {
		setRating(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value13(java.lang.String value) {
		setExplanation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value14(java.lang.String value) {
		setProblemname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value15(java.lang.String value) {
		setProblemdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value16(java.sql.Timestamp value) {
		setDeadline(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value17(java.lang.Integer value) {
		setReward(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value18(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value19(java.lang.String value) {
		setLecturedescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value20(java.lang.String value) {
		setGroupname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value21(java.lang.String value) {
		setGroupdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord value22(java.lang.String value) {
		setRealname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubmissionsfullwithownersRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.String value6, java.sql.Timestamp value7, java.lang.String value8, java.lang.Integer value9, java.lang.String value10, java.lang.String value11, java.lang.Integer value12, java.lang.String value13, java.lang.String value14, java.lang.String value15, java.sql.Timestamp value16, java.lang.Integer value17, java.lang.String value18, java.lang.String value19, java.lang.String value20, java.lang.String value21, java.lang.String value22) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubmissionsfullwithownersRecord
	 */
	public SubmissionsfullwithownersRecord() {
		super(sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS);
	}

	/**
	 * Create a detached, initialised SubmissionsfullwithownersRecord
	 */
	public SubmissionsfullwithownersRecord(java.lang.Integer id, java.lang.Integer assignmentid, java.lang.Integer groupid, java.lang.Integer userid, java.lang.Integer ownerid, java.lang.String submissionfile, java.sql.Timestamp date, java.lang.String status, java.lang.Integer success, java.lang.String info, java.lang.String outputfile, java.lang.Integer rating, java.lang.String explanation, java.lang.String problemname, java.lang.String problemdescription, java.sql.Timestamp deadline, java.lang.Integer reward, java.lang.String lecturename, java.lang.String lecturedescription, java.lang.String groupname, java.lang.String groupdescription, java.lang.String realname) {
		super(sooth.entities.tables.Submissionsfullwithowners.SUBMISSIONSFULLWITHOWNERS);

		setValue(0, id);
		setValue(1, assignmentid);
		setValue(2, groupid);
		setValue(3, userid);
		setValue(4, ownerid);
		setValue(5, submissionfile);
		setValue(6, date);
		setValue(7, status);
		setValue(8, success);
		setValue(9, info);
		setValue(10, outputfile);
		setValue(11, rating);
		setValue(12, explanation);
		setValue(13, problemname);
		setValue(14, problemdescription);
		setValue(15, deadline);
		setValue(16, reward);
		setValue(17, lecturename);
		setValue(18, lecturedescription);
		setValue(19, groupname);
		setValue(20, groupdescription);
		setValue(21, realname);
	}
}
