/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubscriptionsusersgroupslecturesRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.SubscriptionsusersgroupslecturesRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1217652116;

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.realName</code>.
	 */
	public void setRealname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.realName</code>.
	 */
	public java.lang.String getRealname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.groupName</code>.
	 */
	public void setGroupname(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.groupName</code>.
	 */
	public java.lang.String getGroupname() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.groupDescription</code>.
	 */
	public void setGroupdescription(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.groupDescription</code>.
	 */
	public java.lang.String getGroupdescription() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.lectureDescription</code>.
	 */
	public void setLecturedescription(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.lectureDescription</code>.
	 */
	public java.lang.String getLecturedescription() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsusersgroupslectures.ownerId</code>.
	 */
	public void setOwnerid(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsusersgroupslectures.ownerId</code>.
	 */
	public java.lang.Integer getOwnerid() {
		return (java.lang.Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.REALNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.GROUPNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.GROUPDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.LECTUREDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES.OWNERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRealname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGroupname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getGroupdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getLecturedescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getOwnerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value3(java.lang.String value) {
		setRealname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value4(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value5(java.lang.String value) {
		setGroupname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value6(java.lang.String value) {
		setGroupdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value7(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value8(java.lang.String value) {
		setLecturedescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord value9(java.lang.Integer value) {
		setOwnerid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsusersgroupslecturesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.Integer value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubscriptionsusersgroupslecturesRecord
	 */
	public SubscriptionsusersgroupslecturesRecord() {
		super(sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES);
	}

	/**
	 * Create a detached, initialised SubscriptionsusersgroupslecturesRecord
	 */
	public SubscriptionsusersgroupslecturesRecord(java.lang.Integer id, java.lang.String name, java.lang.String realname, java.lang.String email, java.lang.String groupname, java.lang.String groupdescription, java.lang.String lecturename, java.lang.String lecturedescription, java.lang.Integer ownerid) {
		super(sooth.entities.tables.Subscriptionsusersgroupslectures.SUBSCRIPTIONSUSERSGROUPSLECTURES);

		setValue(0, id);
		setValue(1, name);
		setValue(2, realname);
		setValue(3, email);
		setValue(4, groupname);
		setValue(5, groupdescription);
		setValue(6, lecturename);
		setValue(7, lecturedescription);
		setValue(8, ownerid);
	}
}
