/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubscriptionsgroupslecturesRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.SubscriptionsgroupslecturesRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -398411271;

	/**
	 * Setter for <code>asmregen.subscriptionsgroupslectures.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsgroupslectures.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsgroupslectures.userId</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsgroupslectures.userId</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsgroupslectures.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsgroupslectures.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsgroupslectures.groupName</code>.
	 */
	public void setGroupname(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsgroupslectures.groupName</code>.
	 */
	public java.lang.String getGroupname() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsgroupslectures.groupDescription</code>.
	 */
	public void setGroupdescription(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsgroupslectures.groupDescription</code>.
	 */
	public java.lang.String getGroupdescription() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsgroupslectures.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsgroupslectures.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.subscriptionsgroupslectures.lectureDescription</code>.
	 */
	public void setLecturedescription(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.subscriptionsgroupslectures.lectureDescription</code>.
	 */
	public java.lang.String getLecturedescription() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES.GROUPNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES.GROUPDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES.LECTUREDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getGroupname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGroupdescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getLecturedescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsgroupslecturesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsgroupslecturesRecord value2(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsgroupslecturesRecord value3(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsgroupslecturesRecord value4(java.lang.String value) {
		setGroupname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsgroupslecturesRecord value5(java.lang.String value) {
		setGroupdescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsgroupslecturesRecord value6(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsgroupslecturesRecord value7(java.lang.String value) {
		setLecturedescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubscriptionsgroupslecturesRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubscriptionsgroupslecturesRecord
	 */
	public SubscriptionsgroupslecturesRecord() {
		super(sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES);
	}

	/**
	 * Create a detached, initialised SubscriptionsgroupslecturesRecord
	 */
	public SubscriptionsgroupslecturesRecord(java.lang.Integer id, java.lang.Integer userid, java.lang.String status, java.lang.String groupname, java.lang.String groupdescription, java.lang.String lecturename, java.lang.String lecturedescription) {
		super(sooth.entities.tables.Subscriptionsgroupslectures.SUBSCRIPTIONSGROUPSLECTURES);

		setValue(0, id);
		setValue(1, userid);
		setValue(2, status);
		setValue(3, groupname);
		setValue(4, groupdescription);
		setValue(5, lecturename);
		setValue(6, lecturedescription);
	}
}
