/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UascountRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.UascountRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Long> {

	private static final long serialVersionUID = -1935240103;

	/**
	 * Setter for <code>asmregen.uascount.userId</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.uascount.userId</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.uascount.assignmentId</code>.
	 */
	public void setAssignmentid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.uascount.assignmentId</code>.
	 */
	public java.lang.Integer getAssignmentid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.uascount.submissionsCount</code>.
	 */
	public void setSubmissionscount(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.uascount.submissionsCount</code>.
	 */
	public java.lang.Long getSubmissionscount() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Uascount.UASCOUNT.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return sooth.entities.tables.Uascount.UASCOUNT.ASSIGNMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return sooth.entities.tables.Uascount.UASCOUNT.SUBMISSIONSCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAssignmentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getSubmissionscount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UascountRecord value1(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UascountRecord value2(java.lang.Integer value) {
		setAssignmentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UascountRecord value3(java.lang.Long value) {
		setSubmissionscount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UascountRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UascountRecord
	 */
	public UascountRecord() {
		super(sooth.entities.tables.Uascount.UASCOUNT);
	}

	/**
	 * Create a detached, initialised UascountRecord
	 */
	public UascountRecord(java.lang.Integer userid, java.lang.Integer assignmentid, java.lang.Long submissionscount) {
		super(sooth.entities.tables.Uascount.UASCOUNT);

		setValue(0, userid);
		setValue(1, assignmentid);
		setValue(2, submissionscount);
	}
}
