/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserssubmissionsconfirmedRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.UserssubmissionsconfirmedRecord> implements org.jooq.Record13<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 673222468;

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.userId</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.userId</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.realName</code>.
	 */
	public void setRealname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.realName</code>.
	 */
	public java.lang.String getRealname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.groupId</code>.
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.groupId</code>.
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.assignmentId</code>.
	 */
	public void setAssignmentid(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.assignmentId</code>.
	 */
	public java.lang.Integer getAssignmentid() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.submissionId</code>.
	 */
	public void setSubmissionid(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.submissionId</code>.
	 */
	public java.lang.Integer getSubmissionid() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.rating</code>.
	 */
	public void setRating(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.rating</code>.
	 */
	public java.lang.String getRating() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.explanation</code>.
	 */
	public void setExplanation(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.explanation</code>.
	 */
	public java.lang.String getExplanation() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.reward</code>.
	 */
	public void setReward(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.reward</code>.
	 */
	public java.lang.Integer getReward() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.problemName</code>.
	 */
	public void setProblemname(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.problemName</code>.
	 */
	public java.lang.String getProblemname() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.groupName</code>.
	 */
	public void setGroupname(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.groupName</code>.
	 */
	public java.lang.String getGroupname() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>asmregen.userssubmissionsconfirmed.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>asmregen.userssubmissionsconfirmed.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.REALNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.ASSIGNMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.SUBMISSIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.EXPLANATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.REWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.PROBLEMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.GROUPNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRealname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getAssignmentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getSubmissionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getExplanation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getReward();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getProblemname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getGroupname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value1(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value3(java.lang.String value) {
		setRealname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value4(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value5(java.lang.Integer value) {
		setGroupid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value6(java.lang.Integer value) {
		setAssignmentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value7(java.lang.Integer value) {
		setSubmissionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value8(java.lang.String value) {
		setRating(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value9(java.lang.String value) {
		setExplanation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value10(java.lang.Integer value) {
		setReward(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value11(java.lang.String value) {
		setProblemname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value12(java.lang.String value) {
		setGroupname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord value13(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserssubmissionsconfirmedRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.String value8, java.lang.String value9, java.lang.Integer value10, java.lang.String value11, java.lang.String value12, java.lang.String value13) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserssubmissionsconfirmedRecord
	 */
	public UserssubmissionsconfirmedRecord() {
		super(sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED);
	}

	/**
	 * Create a detached, initialised UserssubmissionsconfirmedRecord
	 */
	public UserssubmissionsconfirmedRecord(java.lang.Integer userid, java.lang.String name, java.lang.String realname, java.lang.String email, java.lang.Integer groupid, java.lang.Integer assignmentid, java.lang.Integer submissionid, java.lang.String rating, java.lang.String explanation, java.lang.Integer reward, java.lang.String problemname, java.lang.String groupname, java.lang.String lecturename) {
		super(sooth.entities.tables.Userssubmissionsconfirmed.USERSSUBMISSIONSCONFIRMED);

		setValue(0, userid);
		setValue(1, name);
		setValue(2, realname);
		setValue(3, email);
		setValue(4, groupid);
		setValue(5, assignmentid);
		setValue(6, submissionid);
		setValue(7, rating);
		setValue(8, explanation);
		setValue(9, reward);
		setValue(10, problemname);
		setValue(11, groupname);
		setValue(12, lecturename);
	}
}
