/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersprivilegesRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.UsersprivilegesRecord> implements org.jooq.Record14<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Byte> {

	private static final long serialVersionUID = -1157098492;

	/**
	 * Setter for <code>asmregen.usersprivileges.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.pass</code>.
	 */
	public void setPass(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.pass</code>.
	 */
	public java.lang.String getPass() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.typeId</code>.
	 */
	public void setTypeid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.typeId</code>.
	 */
	public java.lang.Integer getTypeid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.privileges</code>.
	 */
	public void setPrivileges(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.privileges</code>.
	 */
	public java.lang.Integer getPrivileges() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.realName</code>.
	 */
	public void setRealname(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.realName</code>.
	 */
	public java.lang.String getRealname() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.lastAccess</code>.
	 */
	public void setLastaccess(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.lastAccess</code>.
	 */
	public java.sql.Timestamp getLastaccess() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.activationCode</code>.
	 */
	public void setActivationcode(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.activationCode</code>.
	 */
	public java.lang.String getActivationcode() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.encryptionType</code>.
	 */
	public void setEncryptiontype(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.encryptionType</code>.
	 */
	public java.lang.String getEncryptiontype() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.send_email_on_submission_rated</code>.
	 */
	public void setSendEmailOnSubmissionRated(java.lang.Byte value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.send_email_on_submission_rated</code>.
	 */
	public java.lang.Byte getSendEmailOnSubmissionRated() {
		return (java.lang.Byte) getValue(11);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.send_email_on_new_assignment</code>.
	 */
	public void setSendEmailOnNewAssignment(java.lang.Byte value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.send_email_on_new_assignment</code>.
	 */
	public java.lang.Byte getSendEmailOnNewAssignment() {
		return (java.lang.Byte) getValue(12);
	}

	/**
	 * Setter for <code>asmregen.usersprivileges.send_email_on_new_submission</code>.
	 */
	public void setSendEmailOnNewSubmission(java.lang.Byte value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>asmregen.usersprivileges.send_email_on_new_submission</code>.
	 */
	public java.lang.Byte getSendEmailOnNewSubmission() {
		return (java.lang.Byte) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Byte> valuesRow() {
		return (org.jooq.Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.PASS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.TYPEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.PRIVILEGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.REALNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.LASTACCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.ACTIVATIONCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.ENCRYPTIONTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field12() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.SEND_EMAIL_ON_SUBMISSION_RATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field13() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.SEND_EMAIL_ON_NEW_ASSIGNMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field14() {
		return sooth.entities.tables.Usersprivileges.USERSPRIVILEGES.SEND_EMAIL_ON_NEW_SUBMISSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPass();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getTypeid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getPrivileges();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getRealname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getLastaccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getActivationcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getEncryptiontype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value12() {
		return getSendEmailOnSubmissionRated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value13() {
		return getSendEmailOnNewAssignment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value14() {
		return getSendEmailOnNewSubmission();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value3(java.lang.String value) {
		setPass(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value4(java.lang.Integer value) {
		setTypeid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value5(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value6(java.lang.Integer value) {
		setPrivileges(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value7(java.lang.String value) {
		setRealname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value8(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value9(java.sql.Timestamp value) {
		setLastaccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value10(java.lang.String value) {
		setActivationcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value11(java.lang.String value) {
		setEncryptiontype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value12(java.lang.Byte value) {
		setSendEmailOnSubmissionRated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value13(java.lang.Byte value) {
		setSendEmailOnNewAssignment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord value14(java.lang.Byte value) {
		setSendEmailOnNewSubmission(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersprivilegesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.String value5, java.lang.Integer value6, java.lang.String value7, java.lang.String value8, java.sql.Timestamp value9, java.lang.String value10, java.lang.String value11, java.lang.Byte value12, java.lang.Byte value13, java.lang.Byte value14) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersprivilegesRecord
	 */
	public UsersprivilegesRecord() {
		super(sooth.entities.tables.Usersprivileges.USERSPRIVILEGES);
	}

	/**
	 * Create a detached, initialised UsersprivilegesRecord
	 */
	public UsersprivilegesRecord(java.lang.Integer id, java.lang.String name, java.lang.String pass, java.lang.Integer typeid, java.lang.String type, java.lang.Integer privileges, java.lang.String realname, java.lang.String email, java.sql.Timestamp lastaccess, java.lang.String activationcode, java.lang.String encryptiontype, java.lang.Byte sendEmailOnSubmissionRated, java.lang.Byte sendEmailOnNewAssignment, java.lang.Byte sendEmailOnNewSubmission) {
		super(sooth.entities.tables.Usersprivileges.USERSPRIVILEGES);

		setValue(0, id);
		setValue(1, name);
		setValue(2, pass);
		setValue(3, typeid);
		setValue(4, type);
		setValue(5, privileges);
		setValue(6, realname);
		setValue(7, email);
		setValue(8, lastaccess);
		setValue(9, activationcode);
		setValue(10, encryptiontype);
		setValue(11, sendEmailOnSubmissionRated);
		setValue(12, sendEmailOnNewAssignment);
		setValue(13, sendEmailOnNewSubmission);
	}
}
