/**
 * This class is generated by jOOQ
 */
package sooth.entities.tables.records;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XtestslecturesRecord extends org.jooq.impl.TableRecordImpl<sooth.entities.tables.records.XtestslecturesRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1983111144;

	/**
	 * Setter for <code>asmregen.xtestslectures.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>asmregen.xtestslectures.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>asmregen.xtestslectures.template</code>.
	 */
	public void setTemplate(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.template</code>.
	 */
	public java.lang.String getTemplate() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>asmregen.xtestslectures.count</code>.
	 */
	public void setCount(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.count</code>.
	 */
	public java.lang.Integer getCount() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>asmregen.xtestslectures.generated</code>.
	 */
	public void setGenerated(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.generated</code>.
	 */
	public java.lang.String getGenerated() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>asmregen.xtestslectures.lectureId</code>.
	 */
	public void setLectureid(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.lectureId</code>.
	 */
	public java.lang.Integer getLectureid() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>asmregen.xtestslectures.lectureName</code>.
	 */
	public void setLecturename(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.lectureName</code>.
	 */
	public java.lang.String getLecturename() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>asmregen.xtestslectures.lectureDescription</code>.
	 */
	public void setLecturedescription(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.lectureDescription</code>.
	 */
	public java.lang.String getLecturedescription() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>asmregen.xtestslectures.ownerId</code>.
	 */
	public void setOwnerid(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>asmregen.xtestslectures.ownerId</code>.
	 */
	public java.lang.Integer getOwnerid() {
		return (java.lang.Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.TEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.GENERATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.LECTUREID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.LECTURENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.LECTUREDESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return sooth.entities.tables.Xtestslectures.XTESTSLECTURES.OWNERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTemplate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGenerated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getLectureid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getLecturename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getLecturedescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getOwnerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value2(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value3(java.lang.String value) {
		setTemplate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value4(java.lang.Integer value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value5(java.lang.String value) {
		setGenerated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value6(java.lang.Integer value) {
		setLectureid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value7(java.lang.String value) {
		setLecturename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value8(java.lang.String value) {
		setLecturedescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord value9(java.lang.Integer value) {
		setOwnerid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public XtestslecturesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.String value5, java.lang.Integer value6, java.lang.String value7, java.lang.String value8, java.lang.Integer value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached XtestslecturesRecord
	 */
	public XtestslecturesRecord() {
		super(sooth.entities.tables.Xtestslectures.XTESTSLECTURES);
	}

	/**
	 * Create a detached, initialised XtestslecturesRecord
	 */
	public XtestslecturesRecord(java.lang.Integer id, java.lang.String description, java.lang.String template, java.lang.Integer count, java.lang.String generated, java.lang.Integer lectureid, java.lang.String lecturename, java.lang.String lecturedescription, java.lang.Integer ownerid) {
		super(sooth.entities.tables.Xtestslectures.XTESTSLECTURES);

		setValue(0, id);
		setValue(1, description);
		setValue(2, template);
		setValue(3, count);
		setValue(4, generated);
		setValue(5, lectureid);
		setValue(6, lecturename);
		setValue(7, lecturedescription);
		setValue(8, ownerid);
	}
}
